### ISSUE TITLE
Love the idea - but will not build

### ISSUE THREAD

**Issue by MortenGad** [VinnyDyn/StatusReasonKanban#1]
Hi 
Not being to hardcore in TS/NPM i have tried to build the project - it fails.

Then i tried to fix the TS that didn't build - got the solution file but when running there's a missing dependency for vnb_RetrieveOptionSetMetadata....

Would be awesome to try though

**Comment by VinnyBasile** [comment]
Hi Riga1979, are you trying test (npm run start) the project offline or only build?
If the problem is the build, try this:
- Access the interface ExecuteResponse.
- Change the body attribute from string to Readable Stream like these sample.
![image](https://user-images.githubusercontent.com/36446614/65360064-d8e5cf80-dbd4-11e9-9717-a3a5ce097f64.png)

**Comment by MortenGad** [comment]
Hi Vinny, 
Thanks - i think i fixed that (in another way but my guess is it would work :)

But there seem to be a depency to vnb_RetrieveOptionSetMetadata that is missing

I am getting this error in the browser

Resource not found for the segment 'vnb_RetrieveOptionSetMetadata'

**Comment by VinnyBasile** [comment]
Sorry Riga, that's my fault...
The 'vnb_RetrieveOptionSetMetadata' is a Action, and I didn't include the resource in solution.
I've disponibilize a new solution version with this component.

Import the [unmanaged](https://github.com/VinnyDyn/StatusReasonKanban/releases/download/1.0.0/VinnyBControls_1_0_0_0.zip) solution, the problem will be solved.

Thank you for your feedback! :)
